import { useState } from "react";
import { useLocation, useNavigate } from "react-router-dom";
import api from "../../../api/axios";
import useAuth from "../hooks/useAuth";
import Input from "../../../components/Input/Input";
import Button from "../../../components/Button/Button";

import "../styles/VerifyOtp.css"; 

function VerifyOtp() {
  const location = useLocation();
  const navigate = useNavigate();
  const { login } = useAuth();
  const [otp, setOtp] = useState("");
  const [loading, setLoading] = useState(false);

  const email = location.state?.email;

  if (!email) {
    navigate("/login");
    return null;
  }

  const handleSubmit = async (e) => {
    e.preventDefault();
    try {
      setLoading(true);
      const response = await api.post("/auth/verify-otp", { email, otp });

      login(response.data.data.user, response.data.data.token);
      navigate("/dashboard");
    } catch (error) {
      alert(error.response?.data?.message || "Invalid Code");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="verify-otp-wrapper">
      <div className="verify-otp-card">
        <div className="verify-otp-header">
          <div className="icon-container">
            <svg width="48" height="48" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
              <path d="M12 22C6.477 22 2 17.523 2 12C2 6.477 6.477 2 12 2C17.523 2 22 6.477 22 12C22 17.523 17.523 22 12 22ZM11.003 16L18.073 8.929L16.659 7.515L11.003 13.172L8.174 10.343L6.76 11.757L11.003 16Z" fill="#4f46e5"/>
            </svg>
          </div>
          <h2>Authentication 🔐</h2>
          <p>
            Enter the 6-digit code sent to <strong>{email}</strong> or generated by your Authenticator App.
          </p>
        </div>
        
        <form className="verify-otp-form" onSubmit={handleSubmit}>
          <div className="otp-input-container">
            <Input
              type="text"
              maxLength="6"
              value={otp}
              onChange={(e) => setOtp(e.target.value.replace(/\D/g, ''))} // Ensures only numbers
              placeholder="* * * * * *"
              required
            />
          </div>
          <Button type="submit" loading={loading} className="verify-btn">
            Verify & Login
          </Button>
        </form>
      </div>
    </div>
  );
}

export default VerifyOtp;